/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controladores.controladorProducto;
import DTO.dtoListadoFaltantes;
import DTO.dtoUbicacion;
import Modelos.FormaVenta;
import Modelos.TipoMovimiento;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ginin
 */
public class Listado_Faltantes_Productos extends javax.swing.JFrame {

    /**
     * Creates new form Carga_Producto
     */
    DefaultTableModel modelo;

    public Listado_Faltantes_Productos() {
        initComponents();
        fillCombo();
        fillTable(0);

    }

    public void fillTable(int idFormaVenta) {
        modelo = new DefaultTableModel();
        controladorProducto controlador = new controladorProducto();

        ArrayList<dtoListadoFaltantes> dtoListadoFaltantes = controlador.obtenerListadoFaltantes();
        modelo.setColumnIdentifiers(new String[]{"Producto", "Marca", "Forma de venta", "StockMinimo", "Stock total"});

        for (dtoListadoFaltantes item : dtoListadoFaltantes) {
            if (idFormaVenta == 0) {
                modelo.addRow(new Object[]{item.getProducto().getNombreProducto(), item.getProducto().getMarca(), item.getFormaVenta().getDescripcion(),
                    item.getProducto().getStockMinimo(), item.getStockTotal()});
            };
            if(idFormaVenta == item.getFormaVenta().getIdFormaVenta()){
                modelo.addRow(new Object[]{item.getProducto().getNombreProducto(), item.getProducto().getMarca(), item.getFormaVenta().getDescripcion(),
                item.getProducto().getStockMinimo(), item.getStockTotal()});
            }
            tableListadoFaltantes.setModel(modelo);
        }
    }

    private void fillCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<FormaVenta> lista = new ArrayList<>();
        lista.add(new FormaVenta(0, "Todos"));
        lista.add(new FormaVenta(1, "Online"));
        lista.add(new FormaVenta(2, "Presencial"));
        for (FormaVenta item : lista) {
            model.addElement(item);
        }
        cmbFormaVenta.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListadoFaltantes = new javax.swing.JTable();
        cmbFormaVenta = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Listado de faltantes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 100, 30));

        tableListadoFaltantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Marca", "Forma de venta", "Stock total", "Stock minimo"
            }
        ));
        jScrollPane1.setViewportView(tableListadoFaltantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 550, 250));

        cmbFormaVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFormaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaVentaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFormaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Filtrar por forma de venta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/easyCarga.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFormaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaVentaActionPerformed
        FormaVenta formaVenta = (FormaVenta) cmbFormaVenta.getSelectedItem();

        fillTable(formaVenta.getIdFormaVenta());
    }//GEN-LAST:event_cmbFormaVentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listado_Faltantes_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listado_Faltantes_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listado_Faltantes_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listado_Faltantes_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listado_Faltantes_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> cmbFormaVenta;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListadoFaltantes;
    // End of variables declaration//GEN-END:variables
}
