/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controladores.ControladorUbicacion;
import DTO.dtoUbicacion;
import Modelos.Estanteria;
import Modelos.FormaVenta;
import Modelos.LugarUbicacion;
import Modelos.Producto;
import Modelos.Sector;
import Modelos.Stock;
import Modelos.Ubicacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ginin
 */
public class Ubicar_ProductoLista extends javax.swing.JFrame {

    ControladorUbicacion controlador;
    DefaultTableModel modelo;
    int cantProd;

    /**
     *
     * /**
     * Creates new form Carga_Producto
     */
    public Ubicar_ProductoLista() {
        initComponents();
        controlador = new ControladorUbicacion();
        this.setTitle("ubicación de productos");

        this.cargarComboLugarUbicacion();
        //cargarSector();
        //cargarEstanteria();

        cboLugarUbicacion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cargarSector();
            }
        });
        cboSector.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cargarEstanteria();
            }
        });

    }

    public void cargarComboLugarUbicacion() {
        int id;
        ArrayList<LugarUbicacion> lista = (controlador.obtenerLugarUbicacion());
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        for (LugarUbicacion lugar : lista) {
            model.addElement(lugar);
            id = lugar.getCodigo();
        }
        cboLugarUbicacion.setModel(model);
    }

    private int obtenerIdLugar() {
        int id = 0;
        LugarUbicacion lugar = (LugarUbicacion) cboLugarUbicacion.getSelectedItem();
        id = lugar.getCodigo();
        return id;
    }

    private int obtenerIdSector() {
        int id = 0;
        Sector sector = (Sector) cboSector.getSelectedItem();
        id = sector.getId();
        return id;
    }

    public void cargarSector() {
        ArrayList<Sector> lista = controlador.obtenerSector(obtenerIdLugar());
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        for (Sector sector : lista) {
            model.addElement(sector);
        }
        cboSector.setModel(model);

    }

    public void cargarEstanteria() {
        ArrayList<Estanteria> lista = controlador.obtenerEstanteria(obtenerIdSector());
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        for (Estanteria estanteria : lista) {
            model.addElement(estanteria);
        }
        cboEstanteria.setModel(model);
    }
    
    public static void borrarFilas(final DefaultTableModel model) {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        cboEstanteria = new javax.swing.JComboBox();
        cboSector = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboLugarUbicacion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnCargar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Ubicar producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 290, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Estantería");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Cantidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Codigo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 260, 30));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 30));

        getContentPane().add(cboEstanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 250, 30));

        getContentPane().add(cboSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 260, 30));

        btnBuscar.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 0));
        btnBuscar.setText("Buscar producto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 50));

        btnCancelar.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 110, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Sector");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Lugar de almacenamiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        cboLugarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLugarUbicacionActionPerformed(evt);
            }
        });
        getContentPane().add(cboLugarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 250, 30));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código de stock", "Artículo", "Cantidad disponible"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 530, 230));

        btnCargar.setBackground(new java.awt.Color(102, 0, 0));
        btnCargar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 0));
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 110, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/easyCarga.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 600, 710));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 490, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int cod = 0;
        
        try {
            cod = Integer.parseInt(txtCodigo.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "el campo ID  solo acepta números enteros");
        }
        ArrayList<dtoUbicacion> lista = controlador.buscarProductoParaUbicar(cod);
        modelo = new DefaultTableModel();

        modelo.setColumnIdentifiers(new String[]{"Código ubicación", " Artículo", "Cantidad disponible"});

        for (dtoUbicacion dto : lista) {
            modelo.addRow(new Object[]{dto.getIdubi(), dto.getNombreArticulo(), dto.getCantidad()});
         
                 jTable.setModel(modelo); 
                 cantProd= dto.getCantidad();
                
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        int row = jTable.getSelectedRow();
        if (jTable.getSelectedRow() < 0){
             JOptionPane.showMessageDialog(this, "Debe seleccionar un item de la tabla a modificar");
        }
  
        int column = 0;
        int column2 = 2;
   
        int idUbi = (Integer) jTable.getModel().getValueAt(row, column);
        Estanteria estanteria = (Estanteria) cboEstanteria.getSelectedItem();
         int cant = (Integer) jTable.getModel().getValueAt(row, column2);
      
     
         int cantidad = 0 ;
         
          try {

            cantidad = Integer.parseInt(txtCantidad.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "el campo ID y cantidad solo aceptan números enteros");

        }
          
             if(cantidad == cant){
                 //controlador.
          Ubicacion ubi = new Ubicacion(idUbi,estanteria,cant); //idubi, idEstanteria cant
          controlador.modificarUbicacion(idUbi,estanteria.getId(),cant);
        
          
             
         }else if(cant > cantidad ){
             int cantidadSobrante = 0;
             cantidadSobrante = cant - cantidad;
             // Ubicacion ubi = new Ubicacion(idUbi,estanteria,cantidadSobrante); 
              controlador.modificarUbicacion2(idUbi,cantidadSobrante);
              
              Ubicacion ubi2 = new Ubicacion(0,estanteria, cantidad); 
              controlador.crearUbicacion(ubi2);
             
         } else{
             JOptionPane.showMessageDialog(this, "La cantidad a guardar no puede ser mayor a la cantidad existente");
         }
        
           borrarFilas(modelo);
         
         
     
         //  Stock stock = new Stock(0, prod, cant, ubi,);
        //controlador.ubicarProducto(stock);

    }//GEN-LAST:event_btnCargarActionPerformed

    private void cboLugarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLugarUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLugarUbicacionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JComboBox cboEstanteria;
    private javax.swing.JComboBox cboLugarUbicacion;
    private javax.swing.JComboBox cboSector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
